/* eslint-disable no-console */

import * as path from 'node:path';
import { startSpecmaticTest, SpecmaticVerifierError } from '../_harness/specmatic-test';

/**
 * Hand-runnable CRM verifier. It intentionally has no direct engine request:
 * all business traffic is generated by Specmatic's test JVM.
 */
export async function verifyCrm(): Promise<void> {
  const result = await startSpecmaticTest({
    exampleName: 'crm',
    examplesDir: path.resolve('examples/crm/openapi/nuisance-bureau_examples'),
    testMode: 'positiveOnly',
    // The CRM contract has a large generated surface. A method filter keeps
    // this hand-run smoke verifier bounded while still exercising the real
    // Specmatic test JVM and the live Potemkin forwarding path.
    filter: "METHOD='GET' && PATH='/leads/{id}'",
    // Keep the verifier bounded when it is run by hand on a developer laptop.
    // This is passed to the real Specmatic JVM, not applied only in TypeScript.
    maxTestRequestCombinations: 10,
    configPath: path.resolve('tests/conformance/specmatic-verifier.yaml'),
  });

  const report = result.report;
  if (
    result.process.exitCode !== 0 ||
    result.process.signal ||
    report.tests === 0 ||
    report.failures > 0 ||
    report.errors > 0
  ) {
    throw new SpecmaticVerifierError(
      [
        `Specmatic CRM verification failed (exit=${result.process.exitCode ?? 'unknown'}).`,
        `JUnit totals: tests=${report.tests}, failures=${report.failures}, errors=${report.errors}, skipped=${report.skipped}.`,
        result.process.stderr.trim(),
        result.process.stdout.trim(),
      ]
        .filter(Boolean)
        .join('\n'),
    );
  }

  const parsedCases = report.testCases?.length ?? 0;
  if (
    parsedCases !== report.tests ||
    report.testCases?.some(
      (testCase) =>
        !testCase.passed ||
        testCase.method === 'UNKNOWN' ||
        testCase.path === 'UNKNOWN' ||
        testCase.expectedStatus === 'UNKNOWN' ||
        testCase.actualStatus === 'UNKNOWN',
    )
  ) {
    throw new SpecmaticVerifierError(
      `Specmatic CRM JUnit parsing was incomplete: ${parsedCases}/${report.tests} testcases had complete positive identities.`,
    );
  }
  console.log(
    `Specmatic CRM verification passed: ${report.tests} testcase(s), ${parsedCases} parsed testcase(s).`,
  );
}

if (require.main === module) {
  verifyCrm().catch((error: unknown) => {
    const message = error instanceof Error ? error.message : String(error);
    console.error(message);
    process.exitCode = 1;
  });
}
