/** Public generation package: one descriptor-driven path for all derived outputs. */

import {
  generateOpenApiBindings,
  type GeneratedOpenApiBindings,
  type OpenApiBindingOptions,
} from '../openapi/bindings.js';
import {
  generatePotemkinYamlSchema,
  type GeneratedPotemkinYamlSchema,
  type PotemkinYamlSchemaOptions,
} from '../openapi/yamlSchema.js';
import { collectScenarioModel } from '../openapi/scenarioModel.js';
import type {
  ScenarioModel,
  ScenarioEventModel,
  ScenarioBehaviorModel,
  ScenarioBoundaryModel,
  ScenarioComponentModel,
  ScenarioDiagnostic,
  ScenarioDispatchModel,
  ScenarioEmissionModel,
  ScenarioGuardModel,
  ScenarioPolicyModel,
  ScenarioProjectFeature,
  ScenarioProjectFeatureName,
  ScenarioProjectFeatureOwner,
  ScenarioProjectionModel,
  ScenarioQueryModel,
  ScenarioReactionModel,
  ScenarioReducerModel,
  ScenarioReducerPatchModel,
  ScenarioReference,
  ScenarioReferenceKind,
  ScenarioSagaModel,
  ScenarioDiagnosticSeverity,
  ScenarioSourceLocation,
  ScenarioSourcePosition,
  ScenarioWebhookModel,
} from '../openapi/scenarioModel.js';
import {
  generateConfiguredOpenApiBindings,
  generateConfiguredScenarioBindings,
  generateScenarioBindings,
  watchConfiguredOpenApiBindings,
  type ConfiguredBindingOptions,
  type GeneratedScenarioBindings,
  type OpenApiBindingWatchOptions,
  type OpenApiBindingWatcher,
  type ScenarioBindingOptions,
} from './service.js';

export {
  generateOpenApiBindings,
  generatePotemkinYamlSchema,
  collectScenarioModel,
  generateConfiguredOpenApiBindings,
  generateConfiguredScenarioBindings,
  generateScenarioBindings,
  watchConfiguredOpenApiBindings,
};

export type {
  GeneratedOpenApiBindings,
  OpenApiBindingOptions,
  GeneratedPotemkinYamlSchema,
  PotemkinYamlSchemaOptions,
  ConfiguredBindingOptions,
  GeneratedScenarioBindings,
  OpenApiBindingWatchOptions,
  OpenApiBindingWatcher,
  ScenarioBindingOptions,
  ScenarioModel,
  ScenarioEventModel,
  ScenarioBehaviorModel,
  ScenarioBoundaryModel,
  ScenarioComponentModel,
  ScenarioDiagnostic,
  ScenarioDispatchModel,
  ScenarioEmissionModel,
  ScenarioGuardModel,
  ScenarioPolicyModel,
  ScenarioProjectFeature,
  ScenarioProjectFeatureName,
  ScenarioProjectFeatureOwner,
  ScenarioProjectionModel,
  ScenarioQueryModel,
  ScenarioReactionModel,
  ScenarioReducerModel,
  ScenarioReducerPatchModel,
  ScenarioReference,
  ScenarioReferenceKind,
  ScenarioSagaModel,
  ScenarioDiagnosticSeverity,
  ScenarioSourceLocation,
  ScenarioSourcePosition,
  ScenarioWebhookModel,
};
