/** Public TypeScript authoring surface. */

import * as model from "./runtimeModel.js";
import { reducerRule } from "./nativeReducer.js";
import { defineHelper } from "./helpers.js";
import {
  behaviorName,
  boundaryName,
  contractPath,
  eventReference,
  eventType,
  faultName,
  sagaName,
  sagaStepName,
  webhookName,
  field,
  fieldPath,
  helperName,
  linkRelation,
  operationId,
  pathParameter,
  pathSegment,
  resourceName,
  schemaReference,
  scopeName,
  TypeScriptReferenceError,
} from "./references.js";
import type { TypeScriptHelper, TypeScriptHelperDefinition } from "./helpers.js";
import type { DeepReadonly } from "../types.js";
import type {
  AuthoringPredicate,
  AuthoringValue,
  BehaviorBuilder,
  BehaviorDefinition,
  BoundaryBuilder,
  BoundaryDefinition,
  EventBuilder,
  EventDefinition,
  TypedEventDefinition,
  FaultDefinition,
  GlobalDefinition,
  GuardDefinition,
  IdentityDefinition,
  ProjectionDefinition,
  QueryExpression,
  ReactionDefinition,
  ReducerExpression,
  ResponseDefinition,
  ResponseLinkDefinition,
  SagaDefinition,
  SagaCompensationDefinition,
  SagaStepDefinition,
  SecondaryCommandDefinition,
  SimulationBuilder,
  SimulationDefinition,
  TypedEventContext,
  TypedMatchContext,
  TypedReducerContext,
  WebhookDefinition,
} from "./runtimeModel.js";
import type {
  EventContext,
  IdentityContext,
  MatchContext,
  RuntimeReducerContext,
} from "../model/runtime.js";
import type { NativeReducer, NativeReducerBuilder, NativeReducerContext } from "./nativeReducer.js";
import type {
  BoundaryName,
  BehaviorName,
  ContractPath,
  ContractPathSegment,
  EventReference,
  EventSelector,
  EventType,
  FieldPath,
  FieldPathSegment,
  FaultName,
  SagaName,
  SagaStepName,
  WebhookName,
  HelperName,
  HttpMethod,
  LinkRelation,
  OperationId,
  ResourceName,
  ScopeName,
  SchemaReference,
} from "./references.js";

const {
  all,
  any,
  not,
  pipe,
  compose,
  mapReadonly,
  concatReadonly,
  query,
  expression,
  event,
  behavior,
  defineSimulation,
  compileProgram,
  defineEvent,
  defineBehavior,
  defineFault,
  defineReaction,
  defineWebhook,
  defineSaga,
  defineProjection,
  defineGlobal,
  boundary,
  simulation,
} = model;

export {
  all,
  any,
  not,
  pipe,
  compose,
  mapReadonly,
  concatReadonly,
  query,
  expression,
  event,
  behavior,
  reducerRule,
  defineSimulation,
  compileProgram,
  defineEvent,
  defineBehavior,
  defineFault,
  defineReaction,
  defineWebhook,
  defineSaga,
  defineProjection,
  defineGlobal,
  boundary,
  simulation,
  boundaryName,
  behaviorName,
  contractPath,
  eventReference,
  eventType,
  faultName,
  sagaName,
  sagaStepName,
  webhookName,
  field,
  fieldPath,
  helperName,
  linkRelation,
  operationId,
  pathParameter,
  pathSegment,
  resourceName,
  scopeName,
  schemaReference,
  TypeScriptReferenceError,
  defineHelper,
};

export type {
  AuthoringPredicate,
  AuthoringValue,
  BehaviorBuilder,
  BehaviorDefinition,
  BoundaryBuilder,
  BoundaryDefinition,
  EventBuilder,
  EventDefinition,
  TypedEventDefinition,
  FaultDefinition,
  GlobalDefinition,
  GuardDefinition,
  IdentityDefinition,
  ProjectionDefinition,
  QueryExpression,
  ReactionDefinition,
  ReducerExpression,
  ResponseDefinition,
  ResponseLinkDefinition,
  SagaDefinition,
  SagaCompensationDefinition,
  SagaStepDefinition,
  SecondaryCommandDefinition,
  SimulationBuilder,
  SimulationDefinition,
  TypedEventContext,
  TypedMatchContext,
  TypedReducerContext,
  EventContext,
  IdentityContext,
  MatchContext,
  RuntimeReducerContext,
  DeepReadonly,
  WebhookDefinition,
  BoundaryName,
  BehaviorName,
  ContractPath,
  ContractPathSegment,
  EventReference,
  EventSelector,
  EventType,
  FieldPath,
  FieldPathSegment,
  FaultName,
  SagaName,
  SagaStepName,
  WebhookName,
  HelperName,
  HttpMethod,
  LinkRelation,
  OperationId,
  ResourceName,
  ScopeName,
  SchemaReference,
};

export type { NativeReducer, NativeReducerBuilder, NativeReducerContext };
export type { TypeScriptHelper, TypeScriptHelperDefinition };
