/** Public TypeScript authoring surface. */

import * as model from "./runtimeModel.js";
import { reducerRule } from "./nativeReducer.js";
import { defineHelper } from "./helpers.js";
import {
  boundaryName,
  contractPath,
  eventType,
  field,
  fieldPath,
  operationId,
  pathParameter,
  pathSegment,
  schemaReference,
  TypeScriptReferenceError,
} from "./references.js";
import type { TypeScriptHelper } from "./helpers.js";
import type {
  AuthoringPredicate,
  AuthoringValue,
  BehaviorBuilder,
  BehaviorDefinition,
  BoundaryBuilder,
  BoundaryDefinition,
  EventBuilder,
  EventDefinition,
  FaultDefinition,
  GlobalDefinition,
  GuardDefinition,
  IdentityDefinition,
  ProjectionDefinition,
  QueryExpression,
  ReactionDefinition,
  ReducerExpression,
  ResponseDefinition,
  SagaDefinition,
  SecondaryCommandDefinition,
  SimulationBuilder,
  SimulationDefinition,
  TypedEventContext,
  TypedMatchContext,
  TypedReducerContext,
  WebhookDefinition,
  RuntimeHelperDefinition,
} from "./runtimeModel.js";
import type {
  EventContext,
  IdentityContext,
  MatchContext,
  RuntimeReducerContext,
} from "../model/runtime.js";
import type { NativeReducer, NativeReducerBuilder, NativeReducerContext } from "./nativeReducer.js";
import type {
  BoundaryName,
  ContractPath,
  ContractPathSegment,
  EventType,
  FieldPath,
  FieldPathSegment,
  OperationId,
  SchemaReference,
} from "./references.js";

const {
  all,
  any,
  not,
  pipe,
  compose,
  mapReadonly,
  concatReadonly,
  query,
  expression,
  event,
  behavior,
  defineSimulation,
  compileProgram,
  defineEvent,
  defineBehavior,
  defineFault,
  defineReaction,
  defineWebhook,
  defineSaga,
  defineProjection,
  defineGlobal,
  boundary,
  simulation,
} = model;

export {
  all,
  any,
  not,
  pipe,
  compose,
  mapReadonly,
  concatReadonly,
  query,
  expression,
  event,
  behavior,
  reducerRule,
  defineSimulation,
  compileProgram,
  defineEvent,
  defineBehavior,
  defineFault,
  defineReaction,
  defineWebhook,
  defineSaga,
  defineProjection,
  defineGlobal,
  boundary,
  simulation,
  boundaryName,
  contractPath,
  eventType,
  field,
  fieldPath,
  operationId,
  pathParameter,
  pathSegment,
  schemaReference,
  TypeScriptReferenceError,
  defineHelper,
};

export type {
  AuthoringPredicate,
  AuthoringValue,
  BehaviorBuilder,
  BehaviorDefinition,
  BoundaryBuilder,
  BoundaryDefinition,
  EventBuilder,
  EventDefinition,
  FaultDefinition,
  GlobalDefinition,
  GuardDefinition,
  IdentityDefinition,
  ProjectionDefinition,
  QueryExpression,
  ReactionDefinition,
  ReducerExpression,
  ResponseDefinition,
  SagaDefinition,
  SecondaryCommandDefinition,
  SimulationBuilder,
  SimulationDefinition,
  TypedEventContext,
  TypedMatchContext,
  TypedReducerContext,
  EventContext,
  IdentityContext,
  MatchContext,
  RuntimeReducerContext,
  WebhookDefinition,
  RuntimeHelperDefinition,
  BoundaryName,
  ContractPath,
  ContractPathSegment,
  EventType,
  FieldPath,
  FieldPathSegment,
  OperationId,
  SchemaReference,
};

export type { NativeReducer, NativeReducerBuilder, NativeReducerContext };
export type { TypeScriptHelper };
