/** Public TypeScript authoring surface. */

import * as builders from './builders.js';
import { reducerRule } from './nativeReducer.js';
import { defineHelper } from './helpers.js';
import { yamlComponent } from './composition.js';
import type { TypeScriptHelperOptions } from './helpers.js';
import {
  BoundaryName,
  behaviorName,
  boundaryName,
  contractPath,
  eventReference,
  EventType,
  eventType,
  faultName,
  guardName,
  sagaName,
  sagaStepName,
  webhookName,
  field,
  fieldPath,
  queryPath,
  stateFieldName,
  helperName,
  linkRelation,
  HttpMethod,
  operationId,
  OperationId,
  projectionName,
  reactionName,
  pathParameter,
  pathSegment,
  resourceName,
  schemaReference,
  SchemaReference,
  scopeName,
  ReferenceValidationError,
} from '../domain/references.js';
import type { NativeReducer, NativeReducerBuilder, NativeReducerContext } from './nativeReducer.js';
import type {
  BehaviorName,
  ContractPath,
  ContractPathSegment,
  EventReference,
  EventSelector,
  FieldPath,
  FieldPathSegment,
  QueryPath,
  StateFieldName,
  FaultName,
  GuardName,
  SagaName,
  SagaStepName,
  WebhookName,
  HelperName,
  LinkRelation,
  ProjectionName,
  ReactionName,
  ResourceName,
  ScopeName,
  ScenarioEventRegistry,
} from '../domain/references.js';

import type {
  AuthoringPredicate,
  AuthoringValue,
  AuthoringHelpers,
  AuthoringRequest,
  RequestControls,
  BehaviorBuilder,
  BehaviorEmissionDefinition,
  BehaviorDefinition,
  BehaviorFactory,
  EventFactory,
  BoundaryBuilder,
  BoundaryDefinition,
  EventBuilder,
  EventDefinition,
  Expression,
  ExpressionPhase,
  Pipe,
  Compose,
  GlobalDefinition,
  QueryDefinition,
  QueryExpression,
  FaultDefinition,
  FaultErrorClass,
  FaultResponseDefinition,
  FaultSelectorDefinition,
  QueryMappingDefinition,
  QueryValue,
  ReactionDefinition,
  ReducerExpression,
  ReducerDefinition,
  Response,
  ResponseDefinition,
  ResponseLinkDefinition,
  SagaCompensationDefinition,
  SagaDefinition,
  SagaStepDefinition,
  SagaTriggerDefinition,
  SecondaryCommandDefinition,
  SimulationBuilder,
  SimulationDefinition,
  TypeScriptHelper,
  YamlComponentReference,
  TypeScriptHelperDefinition,
  TypeScriptHelperPhase,
  TypeScriptHelperRegistration,
  WebhookDefinition,
  AuthDefinition,
  ControlDefaultsDefinition,
  CoverageDefinition,
  FallbackDefinition,
  FallbackRuleDefinition,
  HateoasDefinition,
  IdempotencyDefinition,
  LifecycleDefinition,
  SecurityHeadersDefinition,
  VersionDefinition,
  VersioningDefinition,
  GuardDefinition,
  IdentityDefinition,
  IdentityKeyDefinition,
  InitializationDefinition,
  SeedDefinition,
  StateDefinition,
  StateFieldType,
  ComputedFieldDefinition,
  InternalFieldDefinition,
  DeprecationDefinition,
  LatencyDefinition,
  ProjectionDefinition,
  QueryContext,
  ReducerContext,
  EventHydrationExpression,
  IdentityExpression,
  FaultExpression,
  WebhookExpression,
  SagaExpression,
  ProjectionExpression,
  ResponseExpression,
  TypedEventDefinition,
  TypedEventContext,
  TypedMatchContext,
  TypedReducerContext,
  EventContext,
  IdentityContext,
  MatchContext,
  PostCommitContext,
  ResponseContext,
  FaultContext,
  WebhookContext,
  SagaContext,
  ProjectionContext,
  DeepReadonly,
} from './types.js';
import type { DataFormat, DataGenerator } from '../contracts/data.js';
import type { JwtValidationConfig } from '../contracts/identity.js';

const all: <Context>(
  ...predicates: readonly AuthoringPredicate<Context>[]
) => AuthoringPredicate<Context> = builders.all;
const any: <Context>(
  ...predicates: readonly AuthoringPredicate<Context>[]
) => AuthoringPredicate<Context> = builders.any;
const not: <Context>(predicate: AuthoringPredicate<Context>) => AuthoringPredicate<Context> =
  builders.not;
const pipe: Pipe = builders.pipe;
const compose: Compose = builders.compose;
const mapReadonly: <Input, Output>(
  values: readonly Input[],
  map: (value: Input) => Output,
) => readonly Output[] = builders.mapReadonly;
const concatReadonly: <Value>(...values: readonly (readonly Value[])[]) => readonly Value[] =
  builders.concatReadonly;
const query: (predicate: QueryExpression) => QueryExpression = builders.query;
const expression: <Context, Value, Phase extends ExpressionPhase>(
  phase: Phase,
  callback: (context: Readonly<Context>) => Value,
) => Expression<Context, Value, Phase> = builders.expression;
const event: EventFactory = builders.event;
const behavior: BehaviorFactory = builders.behavior;
const defineSimulation = builders.defineSimulation;
const defineEvent = builders.defineEvent;
const defineBehavior = builders.defineBehavior;
const defineFault = builders.defineFault;
const defineReaction = builders.defineReaction;
const defineWebhook = builders.defineWebhook;
const defineSaga = builders.defineSaga;
const defineProjection = builders.defineProjection;
const defineGlobal = builders.defineGlobal;
const defineResponse = builders.defineResponse;
const defineQuery = builders.defineQuery;
const boundary: (name: BoundaryName, contractPath: ContractPath) => BoundaryBuilder =
  builders.boundary;
const simulation: (initial?: readonly BoundaryDefinition[]) => SimulationBuilder =
  builders.simulation;

export {
  all,
  any,
  not,
  pipe,
  compose,
  mapReadonly,
  concatReadonly,
  query,
  expression,
  event,
  behavior,
  reducerRule,
  defineSimulation,
  defineEvent,
  defineBehavior,
  defineFault,
  defineReaction,
  defineWebhook,
  defineSaga,
  defineProjection,
  defineGlobal,
  defineResponse,
  defineQuery,
  boundary,
  simulation,
  BoundaryName,
  boundaryName,
  behaviorName,
  contractPath,
  eventReference,
  EventType,
  eventType,
  faultName,
  guardName,
  sagaName,
  sagaStepName,
  webhookName,
  field,
  fieldPath,
  queryPath,
  stateFieldName,
  helperName,
  linkRelation,
  HttpMethod,
  operationId,
  OperationId,
  projectionName,
  reactionName,
  pathParameter,
  pathSegment,
  resourceName,
  scopeName,
  schemaReference,
  SchemaReference,
  ReferenceValidationError,
  defineHelper,
  yamlComponent,
};

export type {
  AuthoringPredicate,
  AuthoringValue,
  AuthoringHelpers,
  AuthoringRequest,
  RequestControls,
  BehaviorBuilder,
  BehaviorEmissionDefinition,
  BehaviorDefinition,
  BehaviorFactory,
  BoundaryBuilder,
  BoundaryDefinition,
  EventBuilder,
  EventDefinition,
  EventFactory,
  TypedEventDefinition,
  Expression,
  ExpressionPhase,
  Pipe,
  Compose,
  FaultDefinition,
  FaultErrorClass,
  FaultResponseDefinition,
  FaultSelectorDefinition,
  GlobalDefinition,
  AuthDefinition,
  JwtValidationConfig,
  ControlDefaultsDefinition,
  CoverageDefinition,
  FallbackDefinition,
  FallbackRuleDefinition,
  HateoasDefinition,
  IdempotencyDefinition,
  LifecycleDefinition,
  SecurityHeadersDefinition,
  VersionDefinition,
  VersioningDefinition,
  GuardDefinition,
  IdentityDefinition,
  IdentityKeyDefinition,
  InitializationDefinition,
  SeedDefinition,
  StateDefinition,
  StateFieldType,
  ComputedFieldDefinition,
  InternalFieldDefinition,
  QueryMappingDefinition,
  DeprecationDefinition,
  LatencyDefinition,
  ProjectionDefinition,
  QueryDefinition,
  QueryExpression,
  QueryContext,
  QueryValue,
  EventHydrationExpression,
  IdentityExpression,
  FaultExpression,
  WebhookExpression,
  SagaExpression,
  ProjectionExpression,
  ResponseExpression,
  ReactionDefinition,
  ReducerExpression,
  ReducerDefinition,
  Response,
  ResponseDefinition,
  ResponseLinkDefinition,
  SagaDefinition,
  SagaCompensationDefinition,
  SagaStepDefinition,
  SagaTriggerDefinition,
  SecondaryCommandDefinition,
  SimulationBuilder,
  SimulationDefinition,
  TypeScriptHelperRegistration,
  YamlComponentReference,
  TypedEventContext,
  TypedMatchContext,
  TypedReducerContext,
  EventContext,
  IdentityContext,
  MatchContext,
  ReducerContext,
  PostCommitContext,
  ResponseContext,
  FaultContext,
  WebhookContext,
  SagaContext,
  ProjectionContext,
  DeepReadonly,
  DataGenerator,
  DataFormat,
  WebhookDefinition,
  BehaviorName,
  ContractPath,
  ContractPathSegment,
  EventReference,
  EventSelector,
  FieldPath,
  FieldPathSegment,
  QueryPath,
  ProjectionName,
  ReactionName,
  StateFieldName,
  FaultName,
  GuardName,
  SagaName,
  SagaStepName,
  WebhookName,
  HelperName,
  LinkRelation,
  ResourceName,
  ScopeName,
  ScenarioEventRegistry,
};

export type { NativeReducer, NativeReducerBuilder, NativeReducerContext };
export type {
  TypeScriptHelper,
  TypeScriptHelperDefinition,
  TypeScriptHelperOptions,
  TypeScriptHelperPhase,
};
